import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Clear existing data
  await prisma.portfolioItem.deleteMany();
  await prisma.blogPost.deleteMany();
  await prisma.service.deleteMany();
  console.log('Cleared existing data');

  // Seed Portfolio Items - Matt Guerra's Art Series
  const portfolioItems = [
    // Self Annihilation Series - 20 images (files: 1.jpg, 3.jpg, 5.jpg, etc.)
    { title: 'Self Annihilation 01', description: 'What started with self-portraits on medium format film became a vehicle to visualize mental illness and addiction. I scratch and burn my own image from the negatives—physically removing myself from the frame.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/1.jpg', tags: ['self-portrait', 'mental health', 'identity', 'mixed media'], featured: true, order: 1 },
    { title: 'Self Annihilation 02', description: 'The destruction of the image mirrors the destruction of self. My whole life I have had an unstable sense of identity—this work visualizes that hollow shell of a person trapped in cycles of mental illness.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/3.jpg', tags: ['self-portrait', 'film', 'experimental'], featured: false, order: 2 },
    { title: 'Self Annihilation 03', description: 'If even one person views this work and decides to fight for mental health advocacy—or feels a little less alone—then every painful moment of its creation will have been worth it.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/5.jpg', tags: ['advocacy', 'vulnerability', 'healing'], featured: false, order: 3 },
    { title: 'Self Annihilation 04', description: 'Through my art, I delve into the darkest parts of my life—not to dwell there, but to create powerful images that speak to the importance of mental health care.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/7.jpg', tags: ['video art', 'documentary', 'personal'], featured: false, order: 4 },
    { title: 'Self Annihilation 05', description: 'The cellular textures and bubble-like overlays represent the biological processes of the body—cells dividing, dying, regenerating—mirroring the cycles of mental illness.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/9.jpg', tags: ['cellular', 'biology', 'cycles'], featured: false, order: 5 },
    { title: 'Self Annihilation 06', description: 'Each scratch on the negative is intentional, a meditation on self-harm transformed into something that might help others understand.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/11.jpg', tags: ['meditation', 'transformation', 'understanding'], featured: false, order: 6 },
    { title: 'Self Annihilation 07', description: 'The body becomes a landscape of trauma, mapped through the manipulation of the photographic surface.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/13.jpg', tags: ['body', 'trauma', 'landscape'], featured: false, order: 7 },
    { title: 'Self Annihilation 08', description: 'Burning the emulsion creates holes where my face should be—absence as presence, void as identity.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/15.jpg', tags: ['absence', 'void', 'identity'], featured: false, order: 8 },
    { title: 'Self Annihilation 09', description: 'The work evolved from single images to installations, books, and video—each medium offering new ways to express the inexpressible.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/17.jpg', tags: ['installation', 'book', 'video'], featured: false, order: 9 },
    { title: 'Self Annihilation 10', description: 'Living with bipolar disorder, anxiety, OCD, and ADHD has left me broken and confused at times—but it has also given me something urgent to say.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/19.jpg', tags: ['bipolar', 'anxiety', 'urgency'], featured: false, order: 10 },
    { title: 'Self Annihilation 11', description: 'The film negative becomes a skin I can shed, scratch, burn—a second body I can destroy without destroying myself.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/21.jpg', tags: ['skin', 'shedding', 'survival'], featured: false, order: 11 },
    { title: 'Self Annihilation 12', description: 'DSM diagnostic criteria appears in the work—clinical language juxtaposed against raw emotional imagery.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/23.jpg', tags: ['DSM', 'diagnosis', 'clinical'], featured: false, order: 12 },
    { title: 'Self Annihilation 13', description: 'Text messages, journal entries, and medical records become part of the visual language—documents of crisis.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/25.jpg', tags: ['text', 'journal', 'documents'], featured: false, order: 13 },
    { title: 'Self Annihilation 14', description: 'The handmade artist book contains 50 pages of images, text, and personal artifacts—a complete portrait of mental illness.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/27.jpg', tags: ['artist book', 'pages', 'artifacts'], featured: false, order: 14 },
    { title: 'Self Annihilation 15', description: 'Quotes from literature appear throughout—Lovecraft, Pasternak—writers who understood darkness.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/29.jpg', tags: ['literature', 'quotes', 'darkness'], featured: false, order: 15 },
    { title: 'Self Annihilation 16', description: 'The work has been exhibited in galleries, but its true home is in the hands of someone who needs to feel less alone.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/31.jpg', tags: ['exhibition', 'connection', 'belonging'], featured: false, order: 16 },
    { title: 'Self Annihilation 17', description: 'Each image is a conversation between destruction and creation—the same hands that harm also heal.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/33.jpg', tags: ['duality', 'destruction', 'creation'], featured: false, order: 17 },
    { title: 'Self Annihilation 18', description: 'The cellular patterns that emerge from the manipulation process mirror the organic structures beneath our skin.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/35.jpg', tags: ['patterns', 'organic', 'beneath'], featured: false, order: 18 },
    { title: 'Self Annihilation 19', description: 'This work is my attempt to make the invisible visible—to give form to formless suffering.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/37.jpg', tags: ['invisible', 'visible', 'suffering'], featured: false, order: 19 },
    { title: 'Self Annihilation 20', description: 'I believe that art has the power to help people feel less alone. That belief sustains this practice.', category: 'Self Annihilation', imageUrl: '/portfolio/self_annihilation/39.jpg', tags: ['belief', 'connection', 'practice'], featured: false, order: 20 },

    // What We Were Left With - uses numbered files (1.jpg, 2.jpg, etc.)
    { title: 'What We Were Left With 01', description: 'Documentary photographs from years of active addiction and the aftermath of trauma. By revisiting and curating this archive of 12,000+ images, I transform evidence of survival into art.', category: 'What We Were Left With', imageUrl: '/portfolio/what_we_were_left_with/1.jpg', tags: ['documentary', 'addiction', 'trauma', 'archive'], featured: true, order: 21 },
    { title: 'What We Were Left With 02', description: 'Trauma can make you question your memories, minimize your suffering. Seeing the evidence—having it exist outside my own mind—confirms that I went through something significant and survived.', category: 'What We Were Left With', imageUrl: '/portfolio/what_we_were_left_with/2.jpg', tags: ['survival', 'documentary', 'recovery'], featured: false, order: 22 },
    { title: 'What We Were Left With 03', description: 'Addiction does not happen in isolation. It is often a response to pain that feels otherwise unmanageable.', category: 'What We Were Left With', imageUrl: '/portfolio/what_we_were_left_with/3.jpg', tags: ['understanding', 'mental health', 'awareness'], featured: false, order: 23 },
    { title: 'What We Were Left With 04', description: 'The fact that I can look back at these images—that I am still here to curate them—is evidence that recovery is possible.', category: 'What We Were Left With', imageUrl: '/portfolio/what_we_were_left_with/4.jpg', tags: ['hope', 'recovery', 'resilience'], featured: false, order: 24 },
    { title: 'What We Were Left With 05', description: 'Influenced by Nan Goldin and Larry Clark, this work embraces the documentary tradition of unflinching witness.', category: 'What We Were Left With', imageUrl: '/portfolio/what_we_were_left_with/5.jpg', tags: ['Nan Goldin', 'Larry Clark', 'documentary'], featured: false, order: 25 },
    { title: 'What We Were Left With 06', description: 'Black and white imagery strips away distraction, leaving only the raw truth of these moments.', category: 'What We Were Left With', imageUrl: '/portfolio/what_we_were_left_with/6.jpg', tags: ['black and white', 'raw', 'truth'], featured: false, order: 26 },
    { title: 'What We Were Left With 07', description: 'These photographs were never meant to be art—they were documentation of daily life during active addiction.', category: 'What We Were Left With', imageUrl: '/portfolio/what_we_were_left_with/7.jpg', tags: ['documentation', 'daily life', 'addiction'], featured: false, order: 27 },
    { title: 'What We Were Left With 08', description: 'By showing both the behavior and its roots, I hope to build understanding rather than judgment.', category: 'What We Were Left With', imageUrl: '/portfolio/what_we_were_left_with/8.jpg', tags: ['understanding', 'judgment', 'roots'], featured: false, order: 28 },
    { title: 'What We Were Left With 09', description: 'The archive spans years—a visual diary of descent and eventual recovery.', category: 'What We Were Left With', imageUrl: '/portfolio/what_we_were_left_with/9.jpg', tags: ['archive', 'diary', 'recovery'], featured: false, order: 29 },
    { title: 'What We Were Left With 10', description: 'Each image is evidence that I was there, that these experiences were real, that I survived them.', category: 'What We Were Left With', imageUrl: '/portfolio/what_we_were_left_with/10.jpg', tags: ['evidence', 'reality', 'survival'], featured: false, order: 30 },
    { title: 'What We Were Left With 11', description: 'The human spirit can survive devastating circumstances. These images prove it.', category: 'What We Were Left With', imageUrl: '/portfolio/what_we_were_left_with/11.jpg', tags: ['spirit', 'survival', 'proof'], featured: false, order: 31 },
    { title: 'What We Were Left With 12', description: 'Looking back at these moments from a place of recovery changes their meaning entirely.', category: 'What We Were Left With', imageUrl: '/portfolio/what_we_were_left_with/12.jpg', tags: ['recovery', 'perspective', 'meaning'], featured: false, order: 32 },

    // Exposure Series - uses _MG_XXXX.jpg format
    { title: 'Exposure 01', description: 'Depression creeps up slowly. The things you enjoy become sources of apathy. Every time you leave bed, it feels like dragging weights that leave trails in the ground behind you.', category: 'Exposure', imageUrl: '/portfolio/exposure/_MG_8279.jpg', tags: ['depression', 'vulnerability', 'emotional', 'self-portrait'], featured: true, order: 33 },
    { title: 'Exposure 02', description: 'Naked and raw in your emotions, you begin to unravel bit by bit and piece by piece until in the end there is nothing left.', category: 'Exposure', imageUrl: '/portfolio/exposure/_MG_8281.jpg', tags: ['mental health', 'awareness', 'raw'], featured: false, order: 34 },
    { title: 'Exposure 03', description: 'I am fighting depression and it seems as if no one understands the weight of that which I am going through. Hopefully now they will understand.', category: 'Exposure', imageUrl: '/portfolio/exposure/_MG_8292.jpg', tags: ['advocacy', 'understanding', 'struggle'], featured: false, order: 35 },
    { title: 'Exposure 04', description: 'Its silent predation on the mind creeps up so slowly that you do not even realize what is happening until it is too late.', category: 'Exposure', imageUrl: '/portfolio/exposure/_MG_8301.jpg', tags: ['documentation', 'awareness', 'healing'], featured: false, order: 36 },
    { title: 'Exposure 05', description: 'Depression is insidious in its approach. You do not see it coming until you are already deep inside it.', category: 'Exposure', imageUrl: '/portfolio/exposure/_MG_8308.jpg', tags: ['insidious', 'depth', 'awareness'], featured: false, order: 37 },
    { title: 'Exposure 06', description: 'The protective layers you have built over a lifetime dissolve, leaving you standing in full view of your own fragility.', category: 'Exposure', imageUrl: '/portfolio/exposure/_MG_8319.jpg', tags: ['protection', 'fragility', 'exposure'], featured: false, order: 38 },
    { title: 'Exposure 07', description: 'I created this series because I needed people to understand this experience—to make the invisible visible.', category: 'Exposure', imageUrl: '/portfolio/exposure/_MG_8331.jpg', tags: ['understanding', 'invisible', 'visible'], featured: false, order: 39 },
    { title: 'Exposure 08', description: 'My hope is that viewers who have experienced this will feel seen, and those who have not might develop new understanding.', category: 'Exposure', imageUrl: '/portfolio/exposure/_MG_8335.jpg', tags: ['seen', 'understanding', 'hope'], featured: false, order: 40 },
    { title: 'Exposure 09', description: 'Depression thrives in isolation and silence. Art can be a way to break both.', category: 'Exposure', imageUrl: '/portfolio/exposure/_MG_8346.jpg', tags: ['isolation', 'silence', 'art'], featured: false, order: 41 },

    // People Who Saved My Life - uses Cyanotype000X.jpg format
    { title: 'People Who Saved My Life 01', description: 'Five portraits printed as cyanotypes of people I am grateful for—people who have saved my life. On the reverse of each is a handwritten letter thanking them for their presence.', category: 'People Who Saved My Life', imageUrl: '/portfolio/people_saved/Cyanotype0001.jpg', tags: ['cyanotype', 'gratitude', 'portrait', 'alternative process'], featured: true, order: 42 },
    { title: 'People Who Saved My Life 02', description: 'Creating work about mental health means constantly confronting darkness. This series is a deliberate shift toward gratitude—a testament to the vital importance of support networks.', category: 'People Who Saved My Life', imageUrl: '/portfolio/people_saved/Cyanotype0003.jpg', tags: ['cyanotype', 'support', 'healing'], featured: false, order: 43 },
    { title: 'People Who Saved My Life 03', description: 'Without these five people, I truly do not believe I would have made it. Connection can be the difference between life and death.', category: 'People Who Saved My Life', imageUrl: '/portfolio/people_saved/Cyanotype0005.jpg', tags: ['community', 'connection', 'life'], featured: false, order: 44 },
    { title: 'People Who Saved My Life 04', description: 'The ethereal blue tones of cyanotype create an almost sacred quality around each subject. Acknowledging the people who save us is itself an act of healing.', category: 'People Who Saved My Life', imageUrl: '/portfolio/people_saved/Cyanotype0007.jpg', tags: ['alternative process', 'portrait', 'emotional'], featured: false, order: 45 },
    { title: 'People Who Saved My Life 05', description: 'This series is a break from the negativity that often surrounds my work—a reflection of a positive mindset and deep gratitude.', category: 'People Who Saved My Life', imageUrl: '/portfolio/people_saved/Cyanotype0009.jpg', tags: ['positivity', 'gratitude', 'healing'], featured: false, order: 46 },

    // Deconstructing Masculinity - uses numbered files (1.jpg, 2.jpg, etc.)
    { title: 'Deconstructing Masculinity 01', description: 'The archetypal man in our society operates within impossibly narrow boundaries. This series confronts those limitations directly through portraits of men with varying gender expressions.', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/1.jpg', tags: ['masculinity', 'gender', 'identity', 'portrait'], featured: true, order: 47 },
    { title: 'Deconstructing Masculinity 02', description: 'These expectations damage everyone. They create a culture where femininity is demonized and men are forbidden from accessing their full emotional range.', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/2.jpg', tags: ['vulnerability', 'emotion', 'expression'], featured: false, order: 48 },
    { title: 'Deconstructing Masculinity 03', description: 'The work asks viewers to examine their own assumptions: What do we expect men to be? Who benefits from those expectations?', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/3.jpg', tags: ['identity', 'society', 'challenge'], featured: false, order: 49 },
    { title: 'Deconstructing Masculinity 04', description: 'Masculinity does not have to mean emotional absence. Strength does not require suppression.', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/4.jpg', tags: ['confrontation', 'questioning', 'freedom'], featured: false, order: 50 },
    { title: 'Deconstructing Masculinity 05', description: 'This series imagines what manhood could look like if we allowed it to include the full spectrum of human experience.', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/5.jpg', tags: ['spectrum', 'humanity', 'possibility'], featured: false, order: 51 },
    { title: 'Deconstructing Masculinity 06', description: 'Each portrait challenges the viewer to see masculinity as expansive rather than restrictive.', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/6.jpg', tags: ['expansive', 'challenge', 'portrait'], featured: false, order: 52 },
    { title: 'Deconstructing Masculinity 07', description: 'The expectation to be stoic, emotionally unavailable, aggressive, and domineering hurts everyone.', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/7.jpg', tags: ['stoic', 'emotion', 'harm'], featured: false, order: 53 },
    { title: 'Deconstructing Masculinity 08', description: 'What becomes possible when we expand our definitions of what a man can be?', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/8.jpg', tags: ['possibility', 'expansion', 'definition'], featured: false, order: 54 },
    { title: 'Deconstructing Masculinity 09', description: 'These portraits present many different types of men and gender expressions—all valid, all worthy.', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/9.jpg', tags: ['diversity', 'validity', 'worth'], featured: false, order: 55 },
    { title: 'Deconstructing Masculinity 10', description: 'The narrow set of descriptions allowed for men in our society creates harm across generations.', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/10.jpg', tags: ['generations', 'harm', 'society'], featured: false, order: 56 },
    { title: 'Deconstructing Masculinity 11', description: 'Vulnerability is not weakness. It is the birthplace of connection and authenticity.', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/11.jpg', tags: ['vulnerability', 'strength', 'authenticity'], featured: false, order: 57 },
    { title: 'Deconstructing Masculinity 12', description: 'Ideas about what it means to identify as a man are changing. This work documents that evolution.', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/13.jpg', tags: ['evolution', 'identity', 'change'], featured: false, order: 58 },
    { title: 'Deconstructing Masculinity 13', description: 'The camera becomes a tool for witnessing—seeing men as they are rather than as society demands they be.', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/14.jpg', tags: ['witness', 'seeing', 'demand'], featured: false, order: 59 },
    { title: 'Deconstructing Masculinity 14', description: 'Each subject was asked to simply be themselves—no performance, no mask, just presence.', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/15.jpg', tags: ['presence', 'authenticity', 'self'], featured: false, order: 60 },
    { title: 'Deconstructing Masculinity 15', description: 'The resulting images challenge viewers to reconsider their assumptions about masculinity.', category: 'Deconstructing Masculinity', imageUrl: '/portfolio/masculinity/16.jpg', tags: ['challenge', 'assumption', 'reconsider'], featured: false, order: 61 },

    // Mixed Media - uses numbered files (1.jpg, 2.jpg, etc.)
    { title: 'Mixed 01', description: 'An in-depth look at Bipolar Disorder. This series seeks to explore the struggles and emotions experienced in bipolar mixed episodes—the only work I could create during a very dark time.', category: 'Mixed', imageUrl: '/portfolio/mixed/1.jpg', tags: ['bipolar', 'mixed episode', 'mental health', 'personal'], featured: true, order: 62 },
    { title: 'Mixed 02', description: 'The chaos of experiencing mania and depression simultaneously, visualized through layered imagery and emotional color palettes.', category: 'Mixed', imageUrl: '/portfolio/mixed/2.jpg', tags: ['chaos', 'emotion', 'struggle'], featured: false, order: 63 },
    { title: 'Mixed 03', description: 'Created during one of the darkest periods of my life, this work represents the only creative output possible during the overwhelming nature of mixed episodes.', category: 'Mixed', imageUrl: '/portfolio/mixed/3.jpg', tags: ['survival', 'expression', 'darkness'], featured: false, order: 64 },
    { title: 'Mixed 04', description: 'Art as therapy—the act of creating during crisis becomes both documentation and survival mechanism.', category: 'Mixed', imageUrl: '/portfolio/mixed/4.jpg', tags: ['therapy', 'documentation', 'healing'], featured: false, order: 65 },
    { title: 'Mixed 05', description: 'When words fail, images speak. These works say what I could not articulate during crisis.', category: 'Mixed', imageUrl: '/portfolio/mixed/5.jpg', tags: ['words', 'images', 'crisis'], featured: false, order: 66 },
    { title: 'Mixed 06', description: 'The visual chaos of these images mirrors the internal chaos of a mixed episode—everything happening at once.', category: 'Mixed', imageUrl: '/portfolio/mixed/6.jpg', tags: ['visual chaos', 'internal', 'everything'], featured: false, order: 67 },
  ];

  for (const item of portfolioItems) {
    await prisma.portfolioItem.create({ data: item });
  }
  console.log(`Created ${portfolioItems.length} portfolio items`);

  // No blog posts or services for now - clean slate
  console.log('Database seeding complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
